IMAGE_SUBMITTED = "image.submitted"
INFERENCE_COMPLETED = "inference.completed"
ANNOTATION_STORED = "annotation.stored"
EMBEDDING_STORED = "embedding.stored"
QUERY_SUBMITTED = "query.submitted"
QUERY_COMPLETED = "query.completed"

VALID_TOPICS = {
    IMAGE_SUBMITTED,
    INFERENCE_COMPLETED,
    ANNOTATION_STORED,
    EMBEDDING_STORED,
    QUERY_SUBMITTED,
    QUERY_COMPLETED,
}
